# Kmeans and NLP

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Data preprocessing

### Importing dataset from sklearn

In [2]:
from sklearn.datasets import load_iris
data = load_iris()

In [3]:
inputs = data['data']
outputs = data['target']
outputNames = data['target_names']
featureNames = list(data['feature_names'])

In [4]:
print(outputNames)

['setosa' 'versicolor' 'virginica']


In [5]:
print(inputs[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [6]:
print(outputs[:100])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [7]:
from random import sample

# indecsi = sample(range(0,len(inputs)),len(inputs))
# # print(indecsi[:5])
# X_train = [] 
# y_train = []

# for index in indecsi: 
#     X_train.append(inputs[index])
#     y_train.append(outputs[index])
X_train = inputs 
y_train = outputs

In [8]:
print(y_train[:5])

[0 0 0 0 0]


## Training the model

In [9]:
from kmeans import Kmeans 

km = Kmeans() 
y_predicted = km.fit_predict(X_train,y_train)


[0.0, 9.055510278004166e-05, 0.00027166530834012495, 0.0005433306166802499, 0.0009055510278004166, 0.0013583265417006249, 0.0019016571583808748, 0.0025355428778411665, 0.0032599837000815, 0.004074979625101875, 0.004980530652902292, 0.00597663678348275, 0.00706329801684325, 0.00824051435298379, 0.009508285791904374, 0.010866612333604999, 0.012315493978085665, 0.013854930725346373, 0.015484922575387123, 0.017205469528207916, 0.019016571583808747, 0.020918228742189623, 0.02291044100335054, 0.0249932083672915, 0.0271665308340125, 0.02943040840351354, 0.03178484107579462, 0.034229828850855744, 0.03676537172869691, 0.039391469709318123, 0.042108122792719374, 0.044915330978900665, 0.047813094267862, 0.05080141265960337, 0.05388028615412478, 0.05704971475142624, 0.06030969845150774, 0.06366023725436928, 0.06710133116001087, 0.07063298016843249, 0.07425518427963415, 0.07796794349361585, 0.0817712578103776, 0.0856651272299194, 0.08964955175224124, 0.09372453137734311, 0.09789006610522503, 0.1021

## Testing the model

In [10]:
for el1,el2 in zip(y_predicted,y_train):
    print(str(el1)+"      "+str(el2))

0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
0      0
1      1
1      1
2      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
0      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
2      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
1      1
2      2
1      2
2      2
2      2
2      2
2      2
1      2
2      2
2      2
2      2
2      2
2

## Accuracy matrix

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_predicted, y_train)
print(cm)
accuracy_score(y_predicted, y_train)

[[50  1  0]
 [ 0 47 14]
 [ 0  2 36]]


0.8866666666666667